### DATA PREPROCESSING AND FEATURE ENGINEERING IN MACHINE LEARNING

In [39]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r'Data\adult_with_headers (1).csv')
data.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [3]:
data.info

<bound method DataFrame.info of        age          workclass  fnlwgt    education  education_num  \
0       39          State-gov   77516    Bachelors             13
1       50   Self-emp-not-inc   83311    Bachelors             13
2       38            Private  215646      HS-grad              9
3       53            Private  234721         11th              7
4       28            Private  338409    Bachelors             13
...    ...                ...     ...          ...            ...
32556   27            Private  257302   Assoc-acdm             12
32557   40            Private  154374      HS-grad              9
32558   58            Private  151910      HS-grad              9
32559   22            Private  201490      HS-grad              9
32560   52       Self-emp-inc  287927      HS-grad              9

            marital_status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White
1       Married-civ-spouse     Exec-managerial         Husband   White
2                 Divorced   Handlers-cleaners   Not-in-family   White
3       Married-civ-spouse   Handlers-cleaners         Husband   Black
4       Married-civ-spouse      Prof-specialty            Wife   Black
...                    ...                 ...             ...     ...
32556   Married-civ-spouse        Tech-support            Wife   White
32557   Married-civ-spouse   Machine-op-inspct         Husband   White
32558              Widowed        Adm-clerical       Unmarried   White
32559        Never-married        Adm-clerical       Own-child   White
32560   Married-civ-spouse     Exec-managerial            Wife   White

           sex  capital_gain  capital_loss  hours_per_week  native_country  \
0         Male          2174             0              40   United-States
1         Male             0             0              13   United-States
2         Male             0             0              40   United-States
3         Male             0             0              40   United-States
4       Female             0             0              40            Cuba
...        ...           ...           ...             ...             ...
32556   Female             0             0              38   United-States
32557     Male             0             0              40   United-States
32558   Female             0             0              40   United-States
32559     Male             0             0              20   United-States
32560   Female         15024             0              40   United-States

       income
0       <=50K
1       <=50K
2       <=50K
3       <=50K
4       <=50K
...       ...
32556   <=50K
32557    >50K
32558   <=50K
32559   <=50K
32560    >50K

[32561 rows x 15 columns]>

In [4]:
data.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [6]:
X = data.drop('income', axis=1)  # all features
y = data['income']   # target

In [7]:
num_cols = X.select_dtypes(include=['int64', 'float64']).columns
cat_cols = X.select_dtypes(include=['object']).columns

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X[num_cols] = scaler.fit_transform(X[num_cols])
#X[num_cols]

In [9]:
# One-hot for small categories
one_hot_cols = [col for col in cat_cols if X[col].nunique() < 5]

# Label encoding for large categories
label_cols = [col for col in cat_cols if X[col].nunique() >= 5]

# One-hot
X = pd.get_dummies(X, columns=one_hot_cols, drop_first=True)

# Label encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for col in label_cols:
    X[col] = le.fit_transform(X[col])

In [10]:
le_y = LabelEncoder()
y = le_y.fit_transform(y)

In [27]:
data1 = pd.DataFrame(X, columns= data.columns)

In [28]:
y = pd.DataFrame(y, columns=['income>50k'])

In [29]:
data1 = X.join(y)

In [30]:
data1.shape

(32561, 15)

In [31]:
data1.describe()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,capital_gain,capital_loss,hours_per_week,native_country,income>50k
count,3.256100e+04,32561.000000,3.256100e+04,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000,3.256100e+04,3.256100e+04,3.256100e+04,32561.000000,32561.000000
mean,-2.662271e-17,3.868892,-9.732565e-17,10.298210,1.479525e-16,2.611836,6.572740,1.446362,3.665858,5.237255e-18,-4.364379e-17,-2.574984e-17,36.718866,0.240810
std,1.000015e+00,1.455960,1.000015e+00,3.870264,1.000015e+00,1.506222,4.228857,1.606771,0.848806,1.000015e+00,1.000015e+00,1.000015e+00,7.823782,0.427581
min,-1.582206e+00,0.000000,-1.681631e+00,0.000000,-3.529656e+00,0.000000,0.000000,0.000000,0.000000,-1.459205e-01,-2.166595e-01,-3.194030e+00,0.000000,0.000000
25%,-7.757679e-01,4.000000,-6.816910e-01,9.000000,-4.200596e-01,2.000000,3.000000,0.000000,4.000000,-1.459205e-01,-2.166595e-01,-3.542945e-02,39.000000,0.000000
50%,-1.159546e-01,4.000000,-1.082193e-01,11.000000,-3.136003e-02,2.000000,7.000000,1.000000,4.000000,-1.459205e-01,-2.166595e-01,-3.542945e-02,39.000000,0.000000
75%,6.904838e-01,4.000000,4.478765e-01,12.000000,7.460392e-01,4.000000,10.000000,3.000000,4.000000,-1.459205e-01,-2.166595e-01,3.695194e-01,39.000000,0.000000
max,3.769612e+00,8.000000,1.226856e+01,15.000000,2.300838e+00,6.000000,14.000000,5.000000,4.000000,1.339458e+01,1.059351e+01,4.742967e+00,41.000000,1.000000

In [34]:
data1.dtypes

age               float64
workclass           int64
fnlwgt            float64
education           int64
education_num     float64
marital_status      int64
occupation          int64
relationship        int64
race                int64
capital_gain      float64
capital_loss      float64
hours_per_week    float64
native_country      int64
sex_ Male            bool
income>50k          int64
dtype: object

##### ●	Discuss the pros and cons of One-Hot Encoding and Label Encoding.

--> pros and cons of One-Hot Encoding. 
*pros:
One-Hot Encoding
Works well with most ML models
Easy to understand
*cons:
Slower with large datasets
Not good for high-cardinality columns

-->pros and cons of Label Encoding. 
*pros:
Simple and fast
Keeps dataset small
*cons:
Introduces false ordering
Can reduce model accuracy if misused

#### Feature Engineering

In [37]:
# feature 1
data1['total_capital'] = data1['capital_gain'] - data1['capital_loss']

In [38]:
# feature 2
data1['hours_per_age'] = data1['hours_per_week'] / data1['age']

In [40]:
# log function

data1['capital_gain_log'] = np.log1p(data1['capital_gain'])